### PR TITLE
Update interim page to post-2023 (CU-866a0b1n7)

### PR DESCRIPTION
**Pull request by VictiniX888**
### Description

(_What have been done/changed_)

- Update interim page to prepare for deploying on www.hacksc.com again

### Testing plan

(_How will we test the changes requested on this PR?_)

- [ ]

### CODE REVIEW

**Comment by snokpok** [comment]
Task linked: [CU-866a0b1n7 Update interim page](https://app.clickup.com/t/866a0b1n7)

**Comment by VictiniX888** [comment]
> Task linked: [CU-866a0b1n7 Update interim page](https://app.clickup.com/t/866a0b1n7)

LMAO

**Comment by snokpok** [comment]
how does that even work i didn't even attach it lmfao

**Review by snokpok — APPROVED** [review]
lgtm

**Pull request merged**
